- url: https://live9.brownrice.com/cam-images/crestedbuttesnowstake.jpg
  output: shots/cb2.png
#   width: 1600
#   height: 2500
  wait: 2500
  # selector: "#webcam_hd_relay__player_2"
  
#  values for further control
#   width: 1600
#   height: 1600
#   quality: 80
#   wait: 2000
#   javascript: |
#     document.querySelectorAll(
#       '[data-ad-rendered],#ensNotifyBanner'
#     ).forEach(el => el.style.display = 'none')
