name: get screenshots

on:
  schedule:
#     - cron: "20 4 * * *"
    - cron: "10 22 * * *"
  push:
  workflow_dispatch:

jobs:
  shot-scraper:
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'simonw/shot-scraper-template' }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache Playwright browsers
      uses: actions/cache@v2
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install Playwright dependencies
      run: |
        shot-scraper install
    - name: CB shot 1
      run: |
        shot-scraper multi config/cb1.yml
    - name: CB shot 2
      run: |
        shot-scraper multi config/cb2.yml
    - name: Monarch shot 1
      run: |
        shot-scraper multi config/monarch1.yml
    - name: Monarch shot 2
      run: |
        shot-scraper multi config/monarch2.yml
    - name: Breck shot
      run: |
        shot-scraper multi config/breck.yml
    - name: Vail shot
      run: |
        shot-scraper multi config/vail.yml
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
